version: "3.9"

services:
  db:
    image: postgres:12-alpine
    container_name: fastapiapp_food
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - fastapiappnetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - "1234:8080"
    networks:
      - fastapiappnetwork

networks:
  fastapiappnetwork: